repository_type: pipeline

nf_core_version: 3.5.2

lint:
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-iridanextexample2_logo_light.png
    - docs/images/nf-core-iridanextexample2_logo_light.png
    - docs/images/nf-core-iridanextexample2_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/CONTRIBUTING.md
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/linting.yml
    - .github/workflows/branch.yml
    - assets/email_template.txt
    - docs/README.md
  nextflow_config:
    - custom_config
    - manifest.name
    - manifest.homePage
    - validation.summary.beforeText
    - validation.summary.afterText
  multiqc_config:
    - report_comment
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-iridanextexample2_logo_light.png
    - docs/images/nf-core-iridanextexample2_logo_light.png
    - docs/images/nf-core-iridanextexample2_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
  included_configs: false

template:
  org: phac-nml
  name: iridanextexample2
  description: An example pipeline for running on IRIDA-Next with nf-schema
  author: Steven Sutcliffe
  version: 0.1.3
  force: true
  outdir: .
  is_nfcore: false
